### ISSUE TITLE
Server won't start with latest v270716 source code

### ISSUE THREAD

**Issue by ghost** [Ignis34Rus/LoE-Ghost.Server#16]
Updating to the latest source code (The DB refactoring and character name filtering change) results in the server throwing an exception the very moment it's started.  I have identified that it isn't any of the changes I make for the server to suit my personal preferences or my database as it throws the same error when compiling a build without any changes and using the stock database files without any changes.  Below is the error that is thrown every single time I try to start the server with the latest source code.  

![missing method error](https://cloud.githubusercontent.com/assets/20789348/26040833/b2a11440-38e5-11e7-9413-98a788c672dd.png)

**Comment by GhostInCell** [comment]
.net framework 4.5.2 installed?

**Comment by ghost** [comment]
Yes, I do have NET framework 4.5.2 installed.

**Comment by GhostInCell** [comment]
Seems you using old Server.exe with new Ghost.Server.dll

**Comment by ghost** [comment]
Found what I was doing wrong.  I was grabbing files from Ghost.Server/bin/Release all this time, when I should have been getting them from Server/bin/Release.  The server works just as it should be.
