### ISSUE TITLE
Regarding ProtoMember order in PonyData

### ISSUE THREAD

**Issue by Schala** [Ignis34Rus/LoE-Ghost.Server#19]
I'm coming from C++ and have used .proto files with Protobuf with it. While I also have my fair knowledge about C#, I'm a tad confused about Protobuf-net, even after reading its docs. For example, in your PonyData code, the ProtoMember-marked fields Eye, Hoof, etc seem to have additional fields (Race, Gender, Name) underneath them. Are these simply not part of the protobuf serialization or is something going on with these fields I'm not understanding?

**Comment by GhostInCell** [comment]
Protobuf-net serialize only fields with ProtoMember attribute, so (Race, Gender, Name) not part of serialization.
