### ISSUE TITLE
any chance for a linux version ?

### ISSUE THREAD

**Issue by antoc** [Ignis34Rus/LoE-Ghost.Server#2]
It look very good, but I want to try to use it in my linux webserver (Debian 8.2).
I have try to compile it with xbuild coming with mono (a .NET adaptation for linux) but I get many errors.
[mono-building-loe-ghost-server-sln.txt](https://github.com/Ignis34Rus/LoE-Ghost.Server/files/378153/mono-building-loe-ghost-server-sln.txt)
I'll search more after 1 week, but if you can answer me, it can be great too ^^

If I understand well, this allow to run a private server with sql support for the players in the February build of legends of equestria ?

**Comment by GhostInCell** [comment]
Yes it works with february client build and allow almost the same features as official server.
I managed to build mono version (I use mono 4.4.1.0 and XBuild Engine 14.0) whith latest commit.

**Comment by antoc** [comment]
Yeah, I'm so happy for this, my dedicated server'll be able to resume service for this game, and for what I see, you really did a great job here
Can it be launched without any windows display manager ? I'll see how to make that if not.

**Comment by antoc** [comment]
Okay, so now, I have these 2 warning, I'll check that later (because it is 3AM), but if you can do it now
[mono-building-loe-ghost-server-sln(1).txt](https://github.com/Ignis34Rus/LoE-Ghost.Server/files/379292/mono-building-loe-ghost-server-sln.1.txt)

**Comment by GhostInCell** [comment]
This server is console application and does not required gui to work. Hope last commit helps.

**Comment by antoc** [comment]
Thanks and sorry for annoying you with that. Now, I have 0 Error and 0 Warning, but it continue to fail the compilation :
[mono-building-loe-ghost-server-sln(2).txt](https://github.com/Ignis34Rus/LoE-Ghost.Server/files/379865/mono-building-loe-ghost-server-sln.2.txt)

**Comment by GhostInCell** [comment]
Hm... I just don't know what went wrong:)
Can you try to build with these parameters: "/verbosity:diagnostic /clp:verbosity"?

**Comment by antoc** [comment]
Thanks for your help, and sorry for my bad level in programming.
[mono-building-loe-ghost-server-sln(3).txt](https://github.com/Ignis34Rus/LoE-Ghost.Server/files/379914/mono-building-loe-ghost-server-sln.3.txt)

**Comment by GhostInCell** [comment]
if last commit not help you can try compiled files:
[Debug.7z](https://drive.google.com/open?id=0B_U2XbzYevYbeXlZZzIyRE9tT2s)

**Comment by antoc** [comment]
[mono-building-loe-ghost-server-sln(4).txt](https://github.com/Ignis34Rus/LoE-Ghost.Server/files/379959/mono-building-loe-ghost-server-sln.4.txt)
Yep, I compile the file on a windows vm, but it is for windows and not for linux, so, I need to do some windows emulation to run it and it open then close. So I really need to compile this for linux. But thanks anyway. I'll see if it exist a cross compiler for linux on windows

**edit** I just installed mono-all to be sure to have every componement of mono and retry to build, and now, I have this log : in the latest commit
[mono-building-loe-ghost-server-sln(6).txt](https://github.com/Ignis34Rus/LoE-Ghost.Server/files/379963/mono-building-loe-ghost-server-sln.6.txt)

**edit2** Here a log with the compiled file and my windows simulator : 
[Server.txt](https://github.com/Ignis34Rus/LoE-Ghost.Server/files/379970/Server.txt)

**Comment by GhostInCell** [comment]
Try use _mono_ insted of _wine_ to run server.exe

**Comment by antoc** [comment]
Ah, it seem to work, I only have "couldn't connect to database", so I'll try to add the sql to my server and your file and I'll see if all work well

**Comment by antoc** [comment]
Ok, it seem to work now, thank you very very much !
What I have in my server : 
[serverlog(1).txt](https://github.com/Ignis34Rus/LoE-Ghost.Server/files/379997/serverlog.1.txt)
I'll need to ask you for new version you compiled if it doesn't annoy you, and I'll see to make a launcher allowing to chose on what server you want to connect with the game.

**Comment by GhostInCell** [comment]
You are welcome!
I'll make release build, after upcoming official "Open Servers Weekend" with new client version support.

**Comment by antoc** [comment]
Thanks then
did you mind if I make a client for this allowing to choose on which server to play and updating the game ?

**Comment by GhostInCell** [comment]
I didn't mind. You can do everything you want!

**Comment by antoc** [comment]
I have still an issue, the game keep loading ponies characters for ever, what port should I open in my firewall if it is the problem ? Else, I don't know where the game is stuck :/

**Comment by GhostInCell** [comment]
You no need to patch dll to connect, modify connections.json and put it in the game folder.
In loe_server.cfg replace all "127.0.0.1" with you IP, except mysql_host.

**Comment by flutterbrony** [comment]
It working, thanks !

Just need to make a sign up page, but I need to know how the password is encripted, I see this in the login.php : base64_encode(hash("tiger192,3", "Celestia".time()."Luna".$this->game_login."~zbKG5tGWqv")) Is it correct ?

**Comment by GhostInCell** [comment]
No it's a session id. Password hashed with sha1:
user name(in lower case) + password.

**Comment by antoc** [comment]
Ok, it's working, thanks, I think I can close this issue now.
