### ISSUE TITLE
Server crashes immediately upon startup

### ISSUE THREAD

**Issue by ghost** [Ignis34Rus/LoE-Ghost.Server#7]
Tried updating my server to using the latest source, but it ends up crashing.  Here's a screenshot of the error message. 
![unhandled exception on startup](https://cloud.githubusercontent.com/assets/20789348/21324769/64bf787a-c5e0-11e6-8662-53f833962c21.png)

**Comment by GhostInCell** [comment]
Seems, db not updated. 
You can use this [script](http://pastebin.com/wdsWvKGZ) to update only items tables

**Comment by ghost** [comment]
I updated the items tables and everything's working like it should, with the exception of not seeing anything in the inventory on the July 2016 client, which I'll open a new issue for.  I feel this issue has been resolved, and can be closed.
