### ISSUE TITLE
Backwards compatability for older clients

### ISSUE THREAD

**Issue by ghost** [Ignis34Rus/LoE-Ghost.Server#8]
After updating my server from the latest source, NPC's who wear items, no longer have visible items.  In addition, items in the inventory don't show up at all.  Shops still work like they should.  This is all with the July 2016 client.  

This NPC should be wearing socks and a potions bag
![2016-12-19 14-25-01-9066](https://cloud.githubusercontent.com/assets/20789348/21329708/566eb76a-c5f7-11e6-9f94-aecceb6a1f16.png)
 
My inventory once showed Sunlight armor and a few other items. 
![no inventory](https://cloud.githubusercontent.com/assets/20789348/21329855/150b8162-c5f8-11e6-9458-2740c6c888d5.png)

With LoE's Limited Access Release now taking place, I feel that the server should be fully backwards compatible with clients from recent OSW's.  The July 2016 client should be fully supported at a bare minimum.  From there, adding full support for the January 2016 client would require only getting the inventory to work as far as I know.

**Comment by GhostInCell** [comment]
Master branch will support only latest client version. 
You can use v27072016 branch until new client will released to public.
